"""create urls table

Revision ID: 332ef0d3c14a
Revises: 
Create Date: 2026-04-29 22:16:19.249311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332ef0d3c14a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.Column('long_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('short_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urls')
    # ### end Alembic commands ###
